Screen/set location
Capstone-Tim-12/warehouse-management-system-mobile pull request #51
Opened 2023-11-22 10:02 UTC by omeralvin

![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/102193167/aa6ff044-27d8-49e3-b914-cb45023aa43e)

dengan seperti ini bagaimana ?

2023-11-22 11:32 UTC, michaelis2101 requested changes
vin bisa tolong tambahin style buat text kotanya? yang line 90, dia pake bodySmall terus kalo ada properti yang beda dari text_collection tambahin copyWith() aja di style text di file kamunya terus sesuain sama style yang ada di figma, biar gak perlu repot buat text collection baru

2023-11-22 11:32 UTC, michaelis2101 commented on lib/screens/main/profile/set_location.dart
> +                  title: Text(allCities[index]),
vin bisa tolong tambahin style buat text kotanya? yang line 90, dia pake bodySmall terus kalo ada properti yang beda dari text_collection tambahin copyWith() aja di style text di file kamunya terus sesuain sama style yang ada di figma, biar gak perlu repot buat text collection baru

2023-11-22 11:39 UTC, omeralvin commented on lib/screens/main/profile/set_location.dart
> +                  title: Text(allCities[index]),
Oke bisa.. Tapi aku belum paham maksud dari copywith nya 🙏🏻

2023-11-23 02:04 UTC, michaelis2101 commented on lib/screens/main/profile/set_location.dart
> +                  title: Text(allCities[index]),
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/126fbfde-8a7a-41ba-b57e-728a3e40596c)


kayak gini vin pakenya, jadi misal ada properti yang beda dari di text collection yang bedanya tinggal samain pake copyWith kek gini

2023-11-24 01:03 UTC, omeralvin commented on lib/screens/main/profile/set_location.dart
> +                  title: Text(allCities[index]),
oke oke

2023-11-24 01:15 UTC, omeralvin commented
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/102193167/d188b6da-4dce-436a-9269-bbe09d8b2060)

seperti ini bagaimana ?

2023-11-24 04:45 UTC, michaelis2101 commented
![image](https://github.com/Capstone-Tim-12/warehouse-management-system-mobile/assets/134735580/8bfa7bb4-0dfe-471c-83aa-6678b4e3b756)

2023-11-24 04:45 UTC, merged